name: CI build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 5.15.0
        platform:
          - gcc_64
          - android
          - wasm_32
          - msvc2019_64
          - msvc2019
          - winrt_x64_msvc2019
          - winrt_x86_msvc2019
          - winrt_armv7_msvc2019
          - mingw81_64
          - mingw81_32
          - clang_64
          - ios

        include:
          - platform: gcc_64
            os: ubuntu-latest
          - platform: android
            os: ubuntu-latest
          - platform: wasm_32
            os: ubuntu-latest
            emsdk: sdk-fastcomp-1.38.27-64bit
          - platform: msvc2019_64
            os: windows-latest
          - platform: msvc2019
            os: windows-latest
          - platform: winrt_x64_msvc2019
            os: windows-latest
          - platform: winrt_x86_msvc2019
            os: windows-latest
          - platform: winrt_armv7_msvc2019
            os: windows-2016
          - platform: mingw81_64
            os: windows-latest
          - platform: mingw81_32
            os: windows-latest
          - platform: clang_64
            os: macos-latest
          - platform: ios
            os: macos-latest

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      - uses: mymindstorm/setup-emsdk@v5
        if: matrix.platform == 'wasm_32'
        with:
          version: ${{matrix.emsdk}}
          actions-cache-folder: emsdk-cache
      - uses: Skycoder42/action-setup-qt@master
        id: qt
        with:
          version: ${{matrix.version}}
          platform: ${{matrix.platform}}
      - run: mkdir build && cd build
      - name: cmake
        working-directory: build
        env:
          CMAKE_PREFIX_PATH: ${{steps.qt.outputs.qtdir}}
        run: cmake -DBUILD_SHARED_LIBS=ON ../src
      - name: cmake
        working-directory: build
        run: cmake --build . --target all
